stages:
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - models/model.pth

    - data_split/test/foxes
    - data_split/test/raccoons
    - data_split/test/weasels
    - data_split/test/skunks
    - data_split/test/hyenas
    - data_split/test/mongooses
    - data_split/test/cats
    - data_split/test/wolves
